### ISSUE TITLE
Small Typo

### ISSUE THREAD

**Issue by gfoss** [trustedsec/spraywmi#2]
SprayWMI is awesome! Just noticed a small typo (metaploit) when running it this morning.

spraywmi.py - line 111
README.md - line 40
https://github.com/trustedsec/spraywmi/search?q=metaploit&type=Code&utf8=%E2%9C%93

It's still raining shells... :-)

Thanks,
Greg

**Comment by trustedsec** [comment]
Fixed, thanks :)
